MTS/urls.py
from django.contrib import admin
from django.urls import path , include

urlpatterns = [
    path('',include("mts_profile.urls")),
    path('online_store/',include("online_store.urls")),
    path('admin/', admin.site.urls),
    path('accounts/',include("accounts.urls")),
    # path('online_store/',include("online_store.urls")),
]

accounts/urls.py
from django.urls import path
from .import views

app_name = "accounts"

urlpatterns = [
    path("login/" , views.login_view , name = "login"),
    path("logout/" , views.logout_view , name = "logout"),
    path("signup/" , views.signup_view , name = "signup"),
]

accounts/models.py
from django.db import models

# Create your models here.

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm , AuthenticationForm
from django.contrib.auth.models import User

class CustomUserCreationForm(UserCreationForm):
    email = forms.EmailField(max_length=254, help_text='Required. Enter a valid email address.')

    class Meta:
        model = User
        fields = ('username','email', 'password1', 'password2')

class CustomAuthenticationForm(AuthenticationForm):
    username = forms.EmailField(max_length=254, help_text='Required. Enter a valid email address.')

    class Meta:
        model = User
        fields = ('username', 'password')

accounts/views.py
from django.shortcuts import render

# Create your views here.

from django.shortcuts import render , redirect
from django.contrib.auth.models import User
from django.contrib.auth import authenticate , login , logout 
from django.contrib.auth.forms import UserCreationForm , AuthenticationForm
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .forms import CustomUserCreationForm , CustomAuthenticationForm



def signup_view(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            
            #log user in
            #log the user in
            user= form.save()
            login(request , user)
            return redirect('signupsuccessful')
    form = CustomUserCreationForm()
    return render(request , "accounts/signup.html" , {"form":form})

def login_view(request):
    if request.method == 'POST':
        form = CustomAuthenticationForm(data = request.POST)
        if form.is_valid():
            #log the user in
            user = form.get_user()
            login(request , user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect('online_store')
    else:
        form = CustomAuthenticationForm()
    return render(request , "accounts/login.html" , {"form":form})


def logout_view(request):
    if request.method == "POST":
        logout(request)
        return redirect('online_store')
    

accounts/templates/accounts/login.html
{% extends 'online_store/layout.html' %}
{% load static %}

{% block body %}

    <div class= "container" style="margin-top:10rem;">
        <div class="row" >
            <div class = "col-md-6" style="margin:auto ;" >
                <h1>Login</h1>
    <form method="post" "{% url 'accounts:login' %}" >
        {% csrf_token %}
        
        {% load widget_tweaks %}
        {{ form.username|add_class:"form-control input modern-form__form-control--textarea"|attr:"placeholder:Username"|attr:"type:Username" }}
        {{ form.password|add_class:"form-control input modern-form__form-control--textarea"|attr:"placeholder:Password"|attr:"type:password" }} 
        <center>
        <input class="btn btn-primary submit-now" type="submit" style="background: #e89e01;border-radius: 0px;" value="Login">
        </center>
        <br>
    </form>
    <center>
    <a style="color: #e89e01;" href="{% url 'accounts:signup' %}" >
        Dont have an account? Singup here
    </a>
    </center>
            </div>
        </div>
        
    </div>
    <br>
    <hr>
    
{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'online_store/layout.html' %}
{% load static %}

{% block body %}

    <div class= "container" style="margin-top:10rem;">
        <div class="row" >
            <div class = "col-md-6" style="margin:auto ;" >
                <h1>Sign Up</h1>
    <form method="post" "{% url 'accounts:signup' %}" >
        {% csrf_token %}
        {% load widget_tweaks %}
        {{ form.username|add_class:"form-control input modern-form__form-control--textarea"|attr:"placeholder:Username"|attr:"type:text" }}
        {% comment %} <p class="text-muted">Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.</p> {% endcomment %}
        {{ form.email|add_class:"form-control input modern-form__form-control--textarea"|attr:"placeholder:Email"|attr:"type:email" }}
        {{ form.password1|add_class:"form-control input modern-form__form-control--textarea"|attr:"placeholder:Password"|attr:"type:password" }}
        {% comment %} <ul class="text-muted">
            <li>Your password can't be too similar to your other personal information.</li>
            <li>Your password must contain at least 8 characters.</li>
            <li>Your password can't be a commonly used password.</li>
            <li>Your password can't be entirely numeric.</li>
        </ul> {% endcomment %}
        {{ form.password2|add_class:"form-control input modern-form__form-control--textarea"|attr:"placeholder:Password Confirmation"|attr:"type:password" }}
        {% comment %} <p class="text-muted">Enter the same password as before, for verification.</p> {% endcomment %}
        <center>
        <input class="btn btn-primary submit-now" type="submit" style="background: #e89e01;border-radius: 0px;" value="Sign Up">
        </center>
        
    </form>
            </div>
        </div>
        
    </div>
    <br>
    <hr>
    
{% endblock %}