MTS/urls.py
from django.contrib import admin
from django.urls import path , include

urlpatterns = [
    path('',include("mts_profile.urls")),
    path('online_store/',include("online_store.urls")),
    path('admin/', admin.site.urls),
    path('accounts/',include("accounts.urls")),
    # path('online_store/',include("online_store.urls")),
]

accounts/urls.py
from django.urls import path
from .import views

app_name = "accounts"

urlpatterns = [
    path("login/" , views.login_view , name = "login"),
    path("logout/" , views.logout_view , name = "logout"),
    path("signup/" , views.signup_view , name = "signup"),
]

online_store/urls.py
from django.urls import path , reverse
from . import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('online_store', views.online_store, name='online_store'),
    path('product/', views.product, name='product'),
    path('category/', views.category, name='category'),
    path('cart/', views.view_cart, name='view_cart'),
    path('profile/', views.profile, name='profile'),
    path('editprofile/', views.editprofile, name='editprofile'),
    path('search/', views.search, name='search'),
    path('checkout/', views.checkout, name='checkout'),
    path("signupsuccessful/" , views.signupsuccessful , name = "signupsuccessful"),
    path("order/" , views.order , name = "order"),
    path('remove_from_cart/<int:cart_item_id>/', views.remove_from_cart, name='remove_from_cart'),
    path('product_details/<int:id>', views.product_details, name = "product_details"),
    path('category_details/<int:id>', views.category_details, name = "category_details"),
    path('add_to_cart/<int:id>',views.add_to_cart , name='add_to_cart' ),
    
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

online_store/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Product(models.Model):
    name = models.CharField(max_length=100)
    desc = models.TextField()
    price = models.IntegerField()
    image = models.ImageField(upload_to='images/products')
    category = models.ForeignKey('Category',on_delete=models.CASCADE)
    condition= models.TextField()
    quantity = models.PositiveIntegerField(default=1)
    shipping = models.TextField()
    availability = models.BooleanField(default=True)
    

    def __str__(self):
        return self.name
    
class Category(models.Model):
    name = models.CharField(max_length=100)
    desc = models.TextField()
    image = models.ImageField(upload_to='images/categories' , blank=True, null=True)
    
    def __str__(self):
        return self.name

class Cart(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    product = models.ForeignKey('Product',on_delete=models.CASCADE)
    added_date = models.DateTimeField(auto_now_add=True)
    quantity = models.PositiveIntegerField(default=1)
    
   
    def __str__(self):
        return self.user.username + " - " + self.product.name
    
class Order(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    product = models.ForeignKey('Product',on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)
    order_date = models.DateTimeField(auto_now_add=True)
    estimated_date_of_arrival = models.CharField(max_length= 20 , blank=True, null=True)
    viewed = models.BooleanField(blank=True, null=True , default=False)
    received = models.BooleanField(blank=True, null=True, default=False)
   
    def __str__(self):
        return self.user.username + " - " + self.product.name
    
# class ReceivedItem(models.Model):
#     user = models.ForeignKey(User,on_delete=models.CASCADE)
#     product = models.ForeignKey('Product',on_delete=models.CASCADE)
#     received_date = models.CharField(max_length= 20 , blank=True, null=True)

#     def __str__(self):
#         return self.user.username + " received " + self.product.name
    
class Profile(models.Model):
    image = models.ImageField(upload_to='images/profiles' , blank=True, null=True)
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    address = models.TextField()
    phone = models.CharField(max_length=20)
   
    def __str__(self):
        return self.user.username
   

online_store/forms.py
from django import forms
from . import models

class ProfileForm(forms.ModelForm):
    class Meta:
        model = models.Profile
        fields = ['image', 'phone', 'address']

class SearchForm(forms.Form):
    query = forms.CharField(max_length=100, required=False)
        

online_store/views.py
from django.shortcuts import render , redirect ,get_object_or_404
from .forms import ProfileForm ,SearchForm
from .models import Category , Product , Cart , Profile , Order 
from django.contrib.auth.decorators import login_required
from django.db import transaction


# Create your views here.

def online_store(request):
    return render(request,'online_store/online_store.html',{
        'title': Product.objects.all()
    })

def category(request):
    return render(request,'online_store/category.html',{
        'title': Category.objects.all()
    })

@login_required(login_url='/accounts/login/')
def profile(request):
    return render(request,'online_store/profile.html',{
        'title': Profile.objects.all(),
        'order': Order.objects.filter(user=request.user).order_by('-order_date'),
        # 'received': ReceivedItem.objects.filter(user=request.user),
    })

@login_required(login_url='/accounts/login/')
def editprofile(request):
    if request.method == 'POST':
        form = ProfileForm(request.POST, request.FILES)
        if form.is_valid():
            # Get the current user
            user = request.user

            # Create or get the associated profile
            profile_instance, created = Profile.objects.get_or_create(user=user)

            # Update the profile fields with the form data
            profile_instance.address = form.cleaned_data['address']
            profile_instance.phone = form.cleaned_data['phone']

            # Check if an image was provided before updating
            if 'image' in request.FILES:
                profile_instance.image = form.cleaned_data['image']

            # Save the updated profile
            profile_instance.save()

            return redirect('profile')
    else:
        form = ProfileForm()

    return render(request, "online_store/editprofile.html", {"form": form})
####### CART VIEWS #############

@login_required(login_url='/accounts/login/')
def add_to_cart(request, id):
    if request.method == 'POST':
        quantity = request.POST.get('quantity', 1)  # Default to 1 if quantity is not provided
        product = get_object_or_404(Product, id=id)

        # Check if the product is already in the user's cart
        existing_cart_item = Cart.objects.filter(user=request.user, product=product).first()

        if existing_cart_item:
            # If the product is already in the cart, update the quantity
            existing_cart_item.quantity += int(quantity)
            existing_cart_item.save()
        else:
            # If the product is not in the cart, create a new cart item
            cart_item = Cart(user=request.user, product=product, quantity=int(quantity))
            cart_item.save()

    return redirect('view_cart')

@login_required(login_url='/accounts/login/')
def remove_from_cart(request, cart_item_id):
    cart_item = Cart.objects.get(id=cart_item_id)
    cart_item.delete()
    return redirect('view_cart')
    


@login_required(login_url='/accounts/login/')
def checkout(request):
    cart_items = Cart.objects.filter(user=request.user)

    with transaction.atomic():  # Use atomic transaction to ensure consistency
        for cart_item in cart_items:
            product = cart_item.product
            quantity_ordered = cart_item.quantity

            if product.quantity >= quantity_ordered > 0:
                Order.objects.create(user=request.user, product=product, quantity=quantity_ordered)
                product.quantity -= quantity_ordered

                if product.quantity == 0:
                    product.availability = False

                product.save()

        cart_items.delete()

    return redirect('order')

@login_required(login_url='/accounts/login/')
def order(request):
   
    orders = Order.objects.filter(user=request.user).order_by('-order_date')

    return render(request, "online_store/orders.html" , {'orders':orders , })
    

@login_required(login_url='/accounts/login/')
def view_cart(request):
    
    orders = Order.objects.filter(user=request.user).order_by('-order_date')
    
    cart_items = Cart.objects.filter(user=request.user)

    total = 0
    subtotal = 0
    shipping = 0
    for order in orders :
        for cart_item in cart_items:
            total = float(order.product.price) * float(cart_item.quantity) + float(order.product.shipping)

    for cart_item in cart_items:
        quantity = cart_item.quantity
        price = cart_item.product.price
        shipping += float(cart_item.product.shipping)  # Ensure it's converted to float
        subtotal += quantity * price

    grand_total = subtotal + shipping

    return render(request, 'online_store/cart.html', {
        'cart_items': cart_items,
        'subtotal': subtotal,
        'shipping': shipping,
        'grand_total': grand_total,
        'total':total
    })

####### PRODUCT VIEWS #############
def product(request):
    return render(request,'online_store/product.html',{
        'title': Product.objects.all()
    })

def product_details(request,id):
    return render(request , "online_store/product_details.html" ,{
        "title" : Product.objects.get(pk=id),
    })

####### CATEGORY VIEWS #############
def category_details(request,id):
    return render(request , "online_store/category_details.html" ,{
        "title" : Category.objects.get(pk=id),
        "list" : Product.objects.all(),
    })

####### SEARCH VIEWS #############

def search(request):
    if request.method == 'GET':
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            results = Product.objects.filter(name__icontains=query)  # Example search by book title
        else:
            results = []
    else:
        form = SearchForm()
        results = []

    return render(request, 'online_store/search.html', {'form': form, 'results': results})

def signupsuccessful(request):
    return render(request , "online_store/signupsuccessful.html",{'title': Profile.objects.all(),})

online_store/templates/online_store/cart.html
{% extends "online_store/layout.html" %}
{% load static %}

{% block body %}


<div class="container" style="margin-top:10rem;">
    <div class="table-responsive">
        
        <table class="table">
            <thead>
                <tr>
                    <th>Item</th>
                    <th>Price</th>
                    <th>Quantity</th>
                    <th>Shipping</th>
                    {% comment %} <th>Total</th> {% endcomment %}
                    
                    
                </tr>
            </thead>
            <tbody>
                {% for item in cart_items %}
                <tr>
                    <td>
                        <div class="d-flex flex-column flex-grow-1 flex-shrink-1 align-items-start" style="margin-left: -1px;">
                            <div><img src="{{item.product.image.url}}" width="51" height="36"></div>
                            <div>
                                <p style="margin-left: 5px;"><strong> {{item.product.name}} </strong></p>
                            </div>
                        </div>
                        <div>
                            <a href="{% url 'remove_from_cart' item.id %}"><button class="btn btn-outline-danger btn-sm" type="submit">Remove</button></a>
                        </div>
                    </td>
                    <td><strong>K {{item.product.price}} </strong></td>
                    <td>
                        <div class="d-flex">
                            <div style="padding: 0.3rem;"></div>
                            <div style="padding: 0.3rem;">
                                <p> {{item.quantity}} </p>
                            </div>
                            <div style="padding: 0.3rem;"></div>
                        </div>
                    </td>
                    <td><strong>K {{item.product.shipping}} </strong></td>
                    {% comment %} <td><strong>K {{total}} </strong></td> {% endcomment %}
                    
                </tr>
                {% endfor %}
            </tbody>
        </table>
        
      
    </div>
    <div style="margin-top: 30px;">
        <div class="table-responsive">
            <table class="table">
                <thead>
                    <tr></tr>
                </thead>
                <tbody>
                    <tr>
                        <td><strong>Subtotal</strong></td>
                        <td>K {{subtotal}} </td>
                    </tr>
                    <tr>
                        <td><strong>Shipping</strong></td>
                        <td>K {{shipping}} &nbsp;</td>
                    </tr>
                    <tr>
                        <td><strong>Grand total</strong></td>
                        <td>K {{grand_total}} &nbsp;</td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
    <a href="{% url 'checkout' %}" >
    <button class="btn btn-primary w-100" type="button" style="background: var(--bs-btn-border-color);border-color: var(--bs-btn-border-color);border-radius: 0px;">Check Out</button>
    </a>
</div>
{% endblock %}

online_store/templates/online_store/category.html
{% extends "online_store/layout.html" %}
{% load static %}

{% block body %}
<div class="container" style="margin-top: 113px;">
    <h1 style="font-size: x-large;">Categories</h1>
    
</div>
<div class="container" style="margin-bottom: 30px;margin-top: 30px;">
    <div class = "row">
        {% for category in title %}
    <div class="col-md-4"><a href="{% url 'category_details' id=category.id%}">
        <div class="card" style="border-radius: 0px;margin-bottom: 29px;"><img class="card-img-top w-100  d-block" style="border-radius: 1px; " src="{{category.image.url}}">
            <div class="card-body">
                <p class="card-text" style="text-align: center;"><strong><span style="color: rgb(40, 40, 40);"> {{category.name}} </span></strong></p>
                <p style="font-weight: bold;color: var(--bs-primary);text-align: center;">{{category.desc}}</p>
            </div>
        </div></a></div>
        {% endfor %}
    </div>
    
</div>

<hr>

{% endblock %}

online_store/templates/online_store/category_details.html
{% extends "online_store/layout.html" %}
{% load static %}

{% block body %}
<div class="container" style="margin-top: 113px;">
    <h1 style="font-size: x-large;">{{title.name}}</h1>
    <p></p>
</div>
<div class="container" style="margin-bottom: 30px;margin-top: 30px;">
    <div class="row">
        {% for item in list %}
        {% if item.category.name == title.name %}
        <div class="col-md-4"><a href="{% url 'product_details' id=item.id%}">
                <div class="card" style="border-radius: 0px;margin-bottom: 29px;"><img class="card-img-top w-100  d-block" style="border-radius: 1px; " src="{{item.image.url}}">
                    <div class="card-body">
                        <p class="card-text" style="text-align: center;"><strong><span style="color: rgb(40, 40, 40);"> {{item.name}} </span></strong></p>
                        <p style="font-weight: bold;color: var(--bs-primary);text-align: center;">K {{item.price}}</p>
                        <center>
                            <button class="btn btn-primary" type="button" style="background-color: rgb(0, 0, 0); border-radius: 0px;">View Item</button>
                        </center>
                    </div>
                </div>
            </a></div>
            {% endif %}
       {% endfor %}
    </div>
</div>
<hr>


{% endblock %}

online_store/templates/online_store/editprofile.html
{% extends "online_store/layout.html" %}
{% load static %}

{% block body %}

<div class="container" >
    <div class="row" >
        <div class="col-md-6" style="margin:auto;margin-top: 113px;">
            <h1 style="font-size: x-large;">Edit Profile</h1>
            <p>Change your Address and Phone Number</p>
            <form  action="{% url 'editprofile' %}" method="post">
                {% csrf_token %}
                {% load widget_tweaks %}
                {{ form.phone|add_class:"form-control input modern-form__form-control--textarea"|attr:"placeholder:Phone Number"|attr:"type:number" }}
                {{ form.address|add_class:"form-control input modern-form__form-control--textarea"|attr:"placeholder:Address"|attr:"type:text" }}
                <center>
                <input class="btn btn-primary submit-now" type="submit" style="background: #e89e01;border-radius: 0px;" value="Save">
            
                </center>
            </form>
        </div>
    </div>

</div>

<hr>

{% endblock %}

online_store/templates/online_store/online_store.html
{% extends "online_store/layout.html" %}
{% load static %}

{% block body %}

<div class="container" style="margin-top: 113px;">
    <h1 style="font-size: x-large;">HOME</h1>
    <p>All Products</p>
</div>
<div class="container" style="margin-bottom: 30px;margin-top: 30px;">
    <div class="row">
        {% for item in title %}
        <div class="col-md-4"><a href="{% url 'product_details' id=item.id%}">
                <div class="card" style="border-radius: 0px;margin-bottom: 29px;"><img class="card-img-top w-100  d-block" style="border-radius: 1px; " src="{{item.image.url}}">
                    <div class="card-body">
                        <p class="card-text" style="text-align: center;"><strong><span style="color: rgb(40, 40, 40);"> {{item.name}} </span></strong></p>
                        <p style="font-weight: bold;color: var(--bs-primary);text-align: center;">K {{item.price}}</p>
                        <center>
                            <button class="btn btn-primary" type="button" style="background-color: rgb(0, 0, 0); border-radius: 0px;">View Item</button>
                        </center>
                    </div>
                </div>
            </a></div>
       {% endfor %}
    </div>
</div>
<hr>


{% endblock %}

online_store/templates/online_store/orders.html
{% extends "online_store/layout.html" %}
{% load static %}

{% block body %}
<div class="container" style="margin-top: 113px;">
    <h1 style="font-size: x-large;">Order Successful !</h1>
    <p>Your order was successful. One of our agents will contact you. Check your order on your profile page.</p>
    <br>
    <center>
        <a href="{% url 'online_store' %}">
            <button class="btn btn-primary submit-now" style="background: #e89e01;border-radius: 0px;" >Continue</button>
         </a>
    </center>
    
</div>
<hr>
{% comment %} <div style="margin-top:10rem">
    {% for order in orders %}
        <p> {{order.product.name}} </p>
        <p> {{order.order_date}} </p>
        <p> {{order.viewed}} </p>
        <p> {{order.received}} </p>

    {% endfor %}
</div> {% endcomment %}

{% endblock %}

online_store/templates/online_store/product_details.html
{% extends "online_store/layout.html" %}
{% load static %}

{% block body %}


    <div class="container" style="margin-top: 113px;">
        <div class="row" style="margin-bottom: 30px;">
            <div class="col-md-6"><img src="{{title.image.url}}"></div>
            <div class="col-md-6">
                <h1 style="font-size: x-large;">{{title.name}} </h1>
                <p style="color: var(--bs-primary);"><strong>K {{title.price}} </strong></p>
                <hr>
                <p><strong>Condition :</strong> {{title.condition}}</p>
                {% comment %} <p><strong>SKU :</strong>&nbsp;<span style="color: rgb(80, 80, 80);">{{tite.sku}}</span></p> {% endcomment %}
                <p><strong>Shipping :</strong> K {{title.shipping}}</p>
               
                

                <!-- Add this input field inside your form -->
                {% if title.availability == True %}
<form method="post" action="{% url 'add_to_cart' title.id %}">
    {% csrf_token %}
    <!-- Other form fields -->

    <label for="quantity"><strong>Quantity :</strong></label>
    <input type="number" id="quantity" name="quantity" value="1" min="1">
    <br><br>
    <button class="btn btn-primary w-100"  style="background: #e89e01; border-radius:0px;" type="submit">Add to Cart</button>
</form>
            {% else %}
            <button class="btn btn-primary w-100"  style="background: #e89e01; border-radius:0px;" type="submit">Not Available</button>
            <br>
            {% endif %}
<br>
<a href="https://wa.me/qr/EDOMQ6TCVP7IG1">
    <button class="btn btn-primary w-75" type="button" style="background: rgba(44,183,66,1);border-color: rgba(44,183,66,1);border-radius: 0px;">Contact us on WhatsApp</button>
    </a>
            </div>
        </div>
    </div>
    <hr>
    <div class="container">
        <h1 style="font-size: x-large;">Description</h1>
        <p><br><span style="color: rgb(80, 80, 80);"> {{title.desc}} </span><br><br></p>
    </div>
    <hr>
{% endblock %}

online_store/templates/online_store/profile.html
{% extends "online_store/layout.html" %}
{% load static %}

{% block body %}

<div class="container" style="margin-top: 113px;">
    <h1 style="font-size: x-large;">Profile</h1>
    <p></p>
</div>
<div class="container" style="margin-top: 30px;">
    <div class="row">
        <div class="col-md-6" style="margin-bottom: 30px;">
            {% comment %}Incase I want to add flex again <div class="d-flex align-items-center flex-sm-row "> {% endcomment %}
            <div>
                <div  style="width:10rem;">
                {% if user.profile.image %}
                    <img class="rounded-circle" src="{{ user.profile.image.url }}" width="84" height="97" style="margin-bottom: 30px;">
                {% else %}
                    <!-- Provide a link to your dummy/default profile image -->
                    <img class="rounded-circle" src="{% static 'img/rj45.jpg' %}" width="84" height="97" style="margin-bottom: 30px;">
                {% endif %}
                </div>
                <div>
                    <p><strong>Username: </strong>{{user.username}}&nbsp;</p>
                    <p><strong>Email: </strong>{{user.email}}&nbsp;</p>
                    <p><strong>Phone Number: </strong>{{user.profile.phone}}&nbsp;</p>
                    <p><strong>Address: </strong>{{user.profile.address}}&nbsp;</p>
                    <a href="{% url 'editprofile' %}">
                    <p style="color: black;" ><i class="icon ion-edit" style="margin-right: 11px; color: black;"></i>Edit Profile</p>
                    </a>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div>
                <h1 style="font-size: large;">Orders</h1>
                <section class="mt-4" style="margin-top: -52px;padding-top: 0px;">
                    <div class="container-fluid">
                        <div class="row">
                            <div class="col">
                                <div class="card shadow">
                                    <div class="card-body">
                                        <div class="table-responsive table mb-0 pt-3 pe-2">
                                            <table class="table table-striped table-sm my-0 mydatatable">
                                                <thead>
                                                    <tr>
                                                        <th>Item</th>
                                                        <th>Price</th>
                                                        <th>Quantity</th>
                                                        <th>Order Date</th>
                                                        <th>Viewed</th>
                                                        <th>Received</th>
                                                        <th>Estimated Date of Arrival</th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                    {% for product in order %}
                                                    <tr>
                                                        <td>
                                                            <div class="d-flex flex-column flex-grow-1 flex-shrink-1 align-items-start" style="margin-left: -1px;">
                                                                <div><img src="{{product.product.image.url}}" width="51" height="36"></div>
                                                                <div>
                                                                    <p style="margin-left: 5px;"><strong>{{product.product.name}}</strong></p>
                                                                </div>
                                                            </div>
                                                        </td>
                                                        <td><strong>K {{product.product.price}}</strong></td>
                                                        <td>
                                                            <div style="padding: 0.3rem;text-align: center;">
                                                                <p>{{product.quantity}}</p>
                                                            </div>
                                                        </td>
                                                        <td>{{product.order_date}}</td>
                                                        <td>{{product.viewed}}</td>
                                                        <td>{{product.received}}</td>
                                                        <td>{{product.estimated_date_of_arrival}}</td>
                                                    </tr>
                                                    {% endfor %}
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
            </div>
        </div>
        
    </div>
    <form class="logout-link" action="{% url 'accounts:logout' %}" method="post">
        {% csrf_token %}
        <input class="btn btn-primary w-100 submit-now" type="submit" style="background: #e89e01;border-radius: 0px;" value="Logout">
    </form>
</div>


<hr>

{% endblock %}

online_store/templates/online_store/search.html
{% extends "online_store/layout.html" %}
{% load static %}

{% block body %}
<div class="container" style="margin-top: 113px;">
    <h1 style="font-size: x-large;">{{title.name}}</h1>
    <p></p>
</div>
<form style="margin-top:15rem;" class="site-form" method="get">
    <div class="container">
        {{ form.as_p }}
    <button class="btn btn-outline-primary" type="submit">Search</button>
    </div>
    
</form>
<hr>


{% endblock %}

online_store/templates/online_store/signupsuccessful.html
{% extends 'online_store/layout.html' %}
{% load static %}

{% block body %}
<div class="container" style="margin-top: 113px;">
    <h1 style="font-size: x-large;">Welcome !</h1>
    <p>Welcome to {{user.username}}! 🎉 . We're thrilled to have you in our community. Explore our amazing products , enjoy a seamless shopping experience , and feel free to reach out if you have any questions. Happy shopping!  </p>
    <br>
    <center>
        <a href="{% url 'online_store' %}">
            <button class="btn btn-primary submit-now" style="background: #e89e01;border-radius: 0px;" >Continue</button>
         </a>
    </center>
    
</div>
    <br>
    <hr>
    
{% endblock %}